name: Tab Finder

on:
  pull_request:
    branches:
      - '*'

jobs:
  tab-finder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v34

    - name: Count tabs in changed files
      run: |
         for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
           echo "$file was changed"
           echo "Tab count in ${file} is $(grep -c $'\t' ${file})" >> report.log
         done
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        path: report.log