name: Tab Finder

on:
  pull_request:
    branches:
      - '*'

jobs:
  tab-finder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Find tabs in code
      run: |
           for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
           echo "The $file has `grep -P '\t' $file | wc -l` tabs" >> report.log
           done
    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
       path: report.log